# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/demo-0.0.1-SNAPSHOT.jar
        remote: demo.jar
        host: a1.tnpl.me
        username: azureuser
        password: ${{ secrets.PASSWORD }}
