# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      env:
          TEST_GITHUB_TOKEN: ${{ secrets.AZURE_CREDENTIALS }}
          TEST_SECRET: ${{ secrets.PASSWORD }}
      run: |
          echo ${#TEST_GITHUB_TOKEN}
          echo ${#TEST_SECRET}
#     - name: AZURE LOGIN 
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.CREDENTIAL }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: grant access to write file
      uses: appleboy/ssh-action@master
      with:
        host: a1.tnpl.me
        username: azureuser
        password: azureuser
        script: |
          sudo chmod a+rws /home/azureuser/
          sudo chmod a+rws /lib/systemd/system/
    - name: Copy lab1 to vm
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/demo-0.0.1-SNAPSHOT.jar
        remote: lab1.jar
        host: a1.tnpl.me
        username: azureuser
        password: azureuser
    - name: Copy service to vm
      uses: garygrossgarten/github-action-scp@release
      with:
        local: lab1.service
        remote: /lib/systemd/system/lab1.service
        host: a1.tnpl.me
        username: azureuser
        password: azureuser
    - name: start daemon-reload
      uses: appleboy/ssh-action@master
      with:
        host: a1.tnpl.me
        username: azureuser
        password: azureuser
        script: |
          sudo systemctl daemon-reload
          sudo systemctl stop lab1
          sudo systemctl start lab1
